package br.netwcomm.gui;

import java.awt.BorderLayout;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;

/**
 *
 * @author Thiago
 */
public class StatsGui extends javax.swing.JFrame 
{
    private ChartPanel chart;
    
    /**
     * Creates new form StatsGui
     */
    public StatsGui(ChartPanel graph) 
    {
        initComponents();
        startGuiUp();
        
        this.chart = graph;
        
        this.pnlGraph.add(graph, BorderLayout.CENTER);
        this.pnlGraph.validate();
    }

    private void startGuiUp()
    {
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblStats = new javax.swing.JToolBar();
        btnSaveGraph = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        pnlGraph = new javax.swing.JPanel();
        pnlInfo = new javax.swing.JPanel();
        scrollStatsInfo = new javax.swing.JScrollPane();
        txtStatsInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transmission Statistics Overview");

        tblStats.setFloatable(false);
        tblStats.setRollover(true);

        btnSaveGraph.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chart_bar.png"))); // NOI18N
        btnSaveGraph.setText("Save Graph");
        btnSaveGraph.setFocusable(false);
        btnSaveGraph.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaveGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveGraphActionPerformed(evt);
            }
        });
        tblStats.add(btnSaveGraph);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/door_in.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.setFocusable(false);
        btnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        tblStats.add(btnClose);

        pnlGraph.setBorder(javax.swing.BorderFactory.createTitledBorder("Statiscs Histogram"));
        pnlGraph.setLayout(new java.awt.BorderLayout());

        pnlInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Statistics Information"));

        txtStatsInfo.setColumns(20);
        txtStatsInfo.setRows(5);
        scrollStatsInfo.setViewportView(txtStatsInfo);

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollStatsInfo)
                .addContainerGap())
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollStatsInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblStats, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tblStats, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveGraphActionPerformed
        String savingPath = new File(".").getAbsolutePath();
        String fileName = "Histogram_" + Long.toString(System.currentTimeMillis()) + ".png";
        
        try
        {
            ChartUtilities.saveChartAsPNG(new File(fileName), this.chart.getChart(), 600, 500);
            JOptionPane.showMessageDialog(this, "Statistics Graph Saved in " + savingPath, 
                    "Graph Saved Information", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex)
        {
            Logger.getLogger(StatsGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveGraphActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSaveGraph;
    private javax.swing.JPanel pnlGraph;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JScrollPane scrollStatsInfo;
    private javax.swing.JToolBar tblStats;
    private javax.swing.JTextArea txtStatsInfo;
    // End of variables declaration//GEN-END:variables
}